'use strict';

// Featured / playoff events (shown on sport pages alongside regular-season games)
const EVENTS = [
  { id:1,  title:"NBA Finals — Game 1",              venue:"Away — WC Champion Arena (TBD)",           date:"Jun 3, 2026",   sport:"nba", emoji:"🏀", color:"#c8102e", venue_key:"msg",
    prices:[{platform:"Ticketmaster",base:540,fees:92},{platform:"StubHub",base:498,fees:80},{platform:"SeatGeek",base:475,fees:68}] },
  { id:18, title:"NBA Finals — Game 3 (Knicks Home)", venue:"Madison Square Garden · New York, NY",     date:"Jun 8, 2026",   sport:"nba", emoji:"🏀", color:"#006bb6", venue_key:"msg", home:"New York Knicks",
    prices:[{platform:"Ticketmaster",base:980,fees:168},{platform:"StubHub",base:915,fees:148},{platform:"SeatGeek",base:862,fees:124}] },
  { id:19, title:"NBA Finals — Game 4 (Knicks Home)", venue:"Madison Square Garden · New York, NY",     date:"Jun 10, 2026",  sport:"nba", emoji:"🏀", color:"#006bb6", venue_key:"msg", home:"New York Knicks",
    prices:[{platform:"Ticketmaster",base:1050,fees:180},{platform:"StubHub",base:982,fees:160},{platform:"SeatGeek",base:920,fees:136}] },
  { id:2,  title:"Stanley Cup Finals — Game 1",      venue:"Amalie Arena · Tampa, FL",                 date:"Jun 1, 2026",   sport:"nhl", emoji:"🏒", color:"#002868", venue_key:"amalie_arena",
    prices:[{platform:"Ticketmaster",base:320,fees:54},{platform:"StubHub",base:298,fees:46},{platform:"SeatGeek",base:285,fees:40}] },
  { id:3,  title:"Yankees vs. Red Sox",              venue:"Yankee Stadium · Bronx, NY",               date:"Jul 4, 2026",   sport:"mlb", emoji:"⚾", color:"#003087", venue_key:"yankee_stadium", home:"New York Yankees", away:"Boston Red Sox",
    prices:[{platform:"Ticketmaster",base:148,fees:26},{platform:"StubHub",base:162,fees:28},{platform:"SeatGeek",base:139,fees:20}] },
  { id:4,  title:"UFC 318 — Main Card",              venue:"T-Mobile Arena · Las Vegas, NV",           date:"Jul 18, 2026",  sport:"ufc", emoji:"🥊", color:"#7f1d1d", venue_key:"t_mobile_arena",
    prices:[{platform:"Ticketmaster",base:295,fees:50},{platform:"StubHub",base:278,fees:44},{platform:"SeatGeek",base:261,fees:38}] },
  { id:5,  title:"LAFC vs. LA Galaxy — El Tráfico", venue:"BMO Stadium · Los Angeles, CA",            date:"Aug 2, 2026",   sport:"mls", emoji:"⚽", color:"#c39b3b", venue_key:"bmo_stadium", home:"LAFC", away:"LA Galaxy",
    prices:[{platform:"Ticketmaster",base:95,fees:16},{platform:"StubHub",base:108,fees:18},{platform:"SeatGeek",base:88,fees:12}] },
  { id:6,  title:"Cowboys vs. Eagles — Week 1",     venue:"AT&T Stadium · Arlington, TX",             date:"Sep 13, 2026",  sport:"nfl", emoji:"🏈", color:"#003594", venue_key:"att_stadium", home:"Dallas Cowboys", away:"Philadelphia Eagles", week:1,
    prices:[{platform:"Ticketmaster",base:385,fees:64},{platform:"StubHub",base:358,fees:56},{platform:"SeatGeek",base:342,fees:50}] },
  { id:7,  title:"MLB Wild Card — Game 3",           venue:"Wrigley Field · Chicago, IL",              date:"Oct 2, 2026",   sport:"mlb", emoji:"⚾", color:"#0e3386", venue_key:"wrigley_field",
    prices:[{platform:"Ticketmaster",base:210,fees:36},{platform:"StubHub",base:225,fees:38},{platform:"SeatGeek",base:198,fees:29}] },
  { id:8,  title:"Chiefs vs. Bills — Week 6",       venue:"GEHA Field at Arrowhead · Kansas City, MO",date:"Oct 11, 2026",  sport:"nfl", emoji:"🏈", color:"#e31837", venue_key:"arrowhead_stadium", home:"Kansas City Chiefs", away:"Buffalo Bills", week:6,
    prices:[{platform:"Ticketmaster",base:420,fees:72},{platform:"StubHub",base:395,fees:63},{platform:"SeatGeek",base:378,fees:56}] },
  { id:9,  title:"World Series — Game 1",            venue:"Dodger Stadium · Los Angeles, CA",         date:"Oct 20, 2026",  sport:"mlb", emoji:"⚾", color:"#005a9c", venue_key:"dodger_stadium",
    prices:[{platform:"Ticketmaster",base:680,fees:118},{platform:"StubHub",base:648,fees:104},{platform:"SeatGeek",base:612,fees:90}] },
  { id:10, title:"NHL Winter Classic",               venue:"Wrigley Field · Chicago, IL",              date:"Jan 1, 2027",   sport:"nhl", emoji:"🏒", color:"#cf0a2c", venue_key:"wrigley_field",
    prices:[{platform:"Ticketmaster",base:245,fees:42},{platform:"StubHub",base:228,fees:36},{platform:"SeatGeek",base:218,fees:31}] },
  { id:11, title:"NFL Playoffs — Divisional Round",  venue:"Lambeau Field · Green Bay, WI",            date:"Jan 17, 2027",  sport:"nfl", emoji:"🏈", color:"#203731", venue_key:"lambeau_field",
    prices:[{platform:"Ticketmaster",base:510,fees:88},{platform:"StubHub",base:485,fees:78},{platform:"SeatGeek",base:462,fees:68}] },
  { id:12, title:"Super Bowl LXI",                   venue:"Allegiant Stadium · Las Vegas, NV",        date:"Feb 7, 2027",   sport:"nfl", emoji:"🏈", color:"#8b1e3f", venue_key:"allegiant_stadium",
    prices:[{platform:"Ticketmaster",base:8200,fees:1400},{platform:"StubHub",base:7650,fees:1240},{platform:"SeatGeek",base:7200,fees:1080}] },
  // World Cup 2026
  { id:13, title:"World Cup — United States · Group Stage",       venue:"MetLife Stadium · East Rutherford, NJ", date:"Jun 12, 2026", sport:"worldcup", emoji:"⚽", color:"#1a3d6e", venue_key:"metlife_stadium", home:"United States",
    prices:[{platform:"Ticketmaster",base:485,fees:82},{platform:"StubHub",base:452,fees:72},{platform:"SeatGeek",base:428,fees:62}] },
  { id:14, title:"World Cup — Brazil vs. Argentina · Round of 16",venue:"Rose Bowl · Pasadena, CA",             date:"Jul 8, 2026",  sport:"worldcup", emoji:"⚽", color:"#009c3b", venue_key:"rose_bowl", home:"Brazil", away:"Argentina",
    prices:[{platform:"Ticketmaster",base:620,fees:108},{platform:"StubHub",base:585,fees:94},{platform:"SeatGeek",base:548,fees:80}] },
  { id:15, title:"World Cup — England vs. France · Quarterfinal", venue:"AT&T Stadium · Arlington, TX",          date:"Jul 12, 2026", sport:"worldcup", emoji:"⚽", color:"#003087", venue_key:"att_stadium", home:"England", away:"France",
    prices:[{platform:"Ticketmaster",base:780,fees:134},{platform:"StubHub",base:732,fees:118},{platform:"SeatGeek",base:695,fees:100}] },
  { id:16, title:"World Cup — Semifinal",                         venue:"MetLife Stadium · East Rutherford, NJ", date:"Jul 17, 2026", sport:"worldcup", emoji:"⚽", color:"#326295", venue_key:"metlife_stadium",
    prices:[{platform:"Ticketmaster",base:980,fees:168},{platform:"StubHub",base:915,fees:148},{platform:"SeatGeek",base:862,fees:126}] },
  { id:17, title:"World Cup — Final",                             venue:"MetLife Stadium · East Rutherford, NJ", date:"Jul 19, 2026", sport:"worldcup", emoji:"⚽", color:"#b8860b", venue_key:"metlife_stadium",
    prices:[{platform:"Ticketmaster",base:2800,fees:480},{platform:"StubHub",base:2620,fees:422},{platform:"SeatGeek",base:2450,fees:368}] },
];
